# Generated by Django 5.1 on 2024-09-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memoire',
            name='resume',
            field=models.TextField(blank=True),
        ),
    ]
