# Generated by Django 5.0.3 on 2024-09-14 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0003_rename_commentaire_memoire_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='Directeur',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='memoire',
            name='annee_ac',
            field=models.CharField(default='2024', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Academic year must be YYYY format')]),
        ),
    ]
