# Generated by Django 5.0.3 on 2024-09-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0005_remove_memoire_date_depot_memoire_encadreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='auteur',
            field=models.CharField(default='', max_length=50),
        ),
    ]
