# Generated by Django 5.0.3 on 2024-09-15 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0006_memoire_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='mot_de_passe',
        ),
    ]
