# Generated by Django 5.0.3 on 2024-09-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0007_remove_etudiant_mot_de_passe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo_profil',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
