# Generated by Django 5.0.3 on 2024-09-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0008_remove_etudiant_user_alter_etudiant_photo_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='user',
        ),
        migrations.RemoveField(
            model_name='memoire',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sujetdeposer',
            name='user',
        ),
    ]
