# Generated by Django 4.2.16 on 2024-09-17 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0014_remove_sujetdeposer_plan_prov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujetdeposer',
            name='date_prop',
            field=models.DateField(default=datetime.datetime(2024, 9, 17, 5, 50, 14, 783289)),
        ),
    ]
