# Generated by Django 4.2.16 on 2024-09-17 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0015_alter_sujetdeposer_date_prop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujetdeposer',
            name='date_prop',
            field=models.DateField(default=datetime.datetime(2024, 9, 17, 8, 53, 41, 454121)),
        ),
    ]
