# Generated by Django 4.2.16 on 2024-09-17 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0016_alter_sujetdeposer_date_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadreur',
            name='user',
        ),
        migrations.AlterField(
            model_name='sujetdeposer',
            name='date_prop',
            field=models.DateField(default=datetime.datetime(2024, 9, 17, 12, 27, 46, 817451)),
        ),
    ]
