# Generated by Django 4.2.16 on 2024-09-17 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0017_remove_encadreur_user_alter_sujetdeposer_date_prop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujetdeposer',
            name='annee_ac',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sujetdeposer',
            name='date_prop',
            field=models.DateField(default=datetime.datetime(2024, 9, 17, 12, 37, 58, 712648)),
        ),
        migrations.AlterField(
            model_name='sujetdeposer',
            name='domaine',
            field=models.TextField(blank=True),
        ),
    ]
