# Generated by Django 4.2.16 on 2024-09-19 08:04

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0018_alter_sujetdeposer_annee_ac_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Encadreur',
        ),
        migrations.RemoveField(
            model_name='memoire',
            name='ulr_fiichier',
        ),
        migrations.AddField(
            model_name='memoire',
            name='url_fichier',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='annee_ac',
            field=models.CharField(default='2024', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Academic year must be YYYY format')]),
        ),
        migrations.AlterField(
            model_name='sujetdeposer',
            name='date_prop',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
