# Generated by Django 4.2.16 on 2024-09-19 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sgt', '0019_delete_director_delete_encadreur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='cosinus',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='Directeur',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='Encadreur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interlocuteur', models.CharField(max_length=255)),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
