# Generated by Django 4.2.16 on 2024-09-17 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0017_remove_encadreur_user_alter_sujetdeposer_date_prop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('directeur', 'Directeur'), ('encadreur', 'Encadreur'), ('faculte', 'Faculté')], default='etudiant', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirecteurProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('department', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='EncadreurProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('specialisation', models.CharField(max_length=100)),
                ('number_of_students_supervised', models.IntegerField()),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='EtudiantProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('student_id', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField()),
            ],
            bases=('accounts.profile',),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
